# Site settings
title: Sam's Log
email: sam.cahn@nyu.edu
description: "The official Sam Cahn portfolio, home of some of Sam's educational game projects and other works of development."
baseurl: ""
url: "http://spc348.github.io"
twitter_username: same348
github_username:  spc348

# Build settings
markdown: kramdown
permalink: pretty
